// Loads the bundled OSM walkable graph (assets/road_graph.bin, ~10 MB) into
// memory at startup. See IMPLEMENTATION.md §7 and ARCHITECTURE.md §6.
//
// Binary format ("RGRP" v1):
//   magic    : 4 bytes ASCII "RGRP"
//   version  : u16 little-endian (currently 1)
//   nodeCount: u32
//   edgeCount: u32
//   nodes    : nodeCount × (lat f64, lng f64)             // index = node id
//   edges    : edgeCount × (
//                u            u32,
//                v            u32,
//                lengthMeters f32,
//                cellCount    u8,
//                cells        cellCount × 7 bytes ASCII   // geohash-7 sequence
//              )
//   geohashIndex:
//                kvCount      u32,
//                kvCount × (
//                  geohash    7 bytes ASCII,
//                  refCount   u16,
//                  refs       refCount × u32 (edge ids)
//                )
//
// All multi-byte integers and floats are LITTLE-ENDIAN. Generated by
// tools/extract_osm.py.

import 'dart:math' as math;
import 'dart:typed_data';

import 'package:flutter/services.dart' show rootBundle;
import 'package:latlong2/latlong.dart';

/// One walkable edge in the bundled OSM graph. Edges are undirected; the
/// adjacency map records each edge id under both endpoints.
class Edge {
  const Edge({
    required this.id,
    required this.u,
    required this.v,
    required this.lengthMeters,
    required this.geohash7Sequence,
  });

  final int id;
  final int u;
  final int v;
  final double lengthMeters;

  /// Ordered, de-duplicated geohash-7 cells the edge polyline crosses. Used
  /// by the risk re-rank to sum predicted risk per cell along a path.
  final List<String> geohash7Sequence;

  /// Returns the opposite endpoint of this edge given one endpoint.
  int other(int node) {
    if (node == u) return v;
    if (node == v) return u;
    throw ArgumentError('Node $node is not an endpoint of edge $id ($u, $v)');
  }
}

/// Bundled OSM road graph for the demo region. Loaded once at app start via
/// [OsmGraph.loadAsset] and held in memory (~10 MB) for the app lifetime.
class OsmGraph {
  OsmGraph({
    required this.nodes,
    required this.edges,
    required this.adjacency,
    required this.geohashIndex,
  });

  /// Node id → LatLng. Index in this list is the node id.
  final List<LatLng> nodes;

  /// All edges. Index in this list is the edge id.
  final List<Edge> edges;

  /// Node id → list of edge ids touching that node.
  final Map<int, List<int>> adjacency;

  /// Geohash-7 → list of edge ids whose [Edge.geohash7Sequence] contains it.
  /// Used by risk lookup to see which edges pass through a given cell.
  final Map<String, List<int>> geohashIndex;

  static const String _magic = 'RGRP';
  static const int _supportedVersion = 1;

  /// Loads the binary graph from Flutter assets. Throws [FormatException] if
  /// the magic / version do not match.
  static Future<OsmGraph> loadAsset(String assetPath) async {
    final ByteData data = await rootBundle.load(assetPath);
    return parseBytes(data);
  }

  /// Pure parser — exposed for tests / for loading from a file path during
  /// generation tooling.
  static OsmGraph parseBytes(ByteData data) {
    int offset = 0;

    // magic
    final List<int> magicBytes = <int>[
      data.getUint8(offset++),
      data.getUint8(offset++),
      data.getUint8(offset++),
      data.getUint8(offset++),
    ];
    final String magic = String.fromCharCodes(magicBytes);
    if (magic != _magic) {
      throw FormatException(
        'OsmGraph: bad magic. Expected "$_magic", got "$magic".',
      );
    }

    final int version = data.getUint16(offset, Endian.little);
    offset += 2;
    if (version != _supportedVersion) {
      throw FormatException(
        'OsmGraph: unsupported version $version, expected $_supportedVersion.',
      );
    }

    final int nodeCount = data.getUint32(offset, Endian.little);
    offset += 4;
    final int edgeCount = data.getUint32(offset, Endian.little);
    offset += 4;

    // nodes
    final List<LatLng> nodes = List<LatLng>.filled(
      nodeCount,
      const LatLng(0, 0),
      growable: false,
    );
    for (int i = 0; i < nodeCount; i++) {
      final double lat = data.getFloat64(offset, Endian.little);
      offset += 8;
      final double lng = data.getFloat64(offset, Endian.little);
      offset += 8;
      nodes[i] = LatLng(lat, lng);
    }

    // edges
    final List<Edge> edges = <Edge>[];
    final Map<int, List<int>> adjacency = <int, List<int>>{};

    for (int i = 0; i < edgeCount; i++) {
      final int u = data.getUint32(offset, Endian.little);
      offset += 4;
      final int v = data.getUint32(offset, Endian.little);
      offset += 4;
      final double length = data.getFloat32(offset, Endian.little);
      offset += 4;
      final int cellCount = data.getUint8(offset);
      offset += 1;

      final List<String> cells = List<String>.filled(cellCount, '', growable: false);
      for (int c = 0; c < cellCount; c++) {
        final List<int> cellBytes = <int>[
          data.getUint8(offset++),
          data.getUint8(offset++),
          data.getUint8(offset++),
          data.getUint8(offset++),
          data.getUint8(offset++),
          data.getUint8(offset++),
          data.getUint8(offset++),
        ];
        cells[c] = String.fromCharCodes(cellBytes);
      }

      final Edge edge = Edge(
        id: i,
        u: u,
        v: v,
        lengthMeters: length,
        geohash7Sequence: cells,
      );
      edges.add(edge);
      (adjacency[u] ??= <int>[]).add(i);
      (adjacency[v] ??= <int>[]).add(i);
    }

    // geohash index
    final Map<String, List<int>> geohashIndex = <String, List<int>>{};
    final int kvCount = data.getUint32(offset, Endian.little);
    offset += 4;
    for (int i = 0; i < kvCount; i++) {
      final List<int> ghBytes = <int>[
        data.getUint8(offset++),
        data.getUint8(offset++),
        data.getUint8(offset++),
        data.getUint8(offset++),
        data.getUint8(offset++),
        data.getUint8(offset++),
        data.getUint8(offset++),
      ];
      final String gh = String.fromCharCodes(ghBytes);
      final int refCount = data.getUint16(offset, Endian.little);
      offset += 2;
      final List<int> refs = List<int>.filled(refCount, 0, growable: false);
      for (int r = 0; r < refCount; r++) {
        refs[r] = data.getUint32(offset, Endian.little);
        offset += 4;
      }
      geohashIndex[gh] = refs;
    }

    return OsmGraph(
      nodes: nodes,
      edges: edges,
      adjacency: adjacency,
      geohashIndex: geohashIndex,
    );
  }

  /// Naive linear scan for the nearest node. The bundled graph is small
  /// (~5 km × 5 km, O(10⁴–10⁵) nodes) so this is fast enough for one-off
  /// snap calls. Replace with a KD-tree if profiling demands.
  int nearestNode(LatLng p) {
    if (nodes.isEmpty) {
      throw StateError('OsmGraph has no nodes.');
    }
    int bestId = 0;
    double bestSq = double.infinity;
    for (int i = 0; i < nodes.length; i++) {
      final LatLng n = nodes[i];
      // Use simple squared-degree distance for the scan; only the relative
      // order matters and the bbox is tiny so distortion is negligible.
      final double dLat = n.latitude - p.latitude;
      final double dLng = n.longitude - p.longitude;
      final double sq = dLat * dLat + dLng * dLng;
      if (sq < bestSq) {
        bestSq = sq;
        bestId = i;
      }
    }
    return bestId;
  }

  /// Edge ids whose polyline passes through the given geohash-7 cell.
  /// Returns an empty iterable if the cell is not indexed.
  Iterable<int> edgesThroughCell(String geohash7) {
    return geohashIndex[geohash7] ?? const <int>[];
  }

  /// Convenience: convert a sequence of node ids (path) to a polyline.
  List<LatLng> nodesToPolyline(List<int> path) {
    return <LatLng>[for (final int id in path) nodes[id]];
  }

  /// Total path length in meters for a node-id sequence, summing the matching
  /// edges' [Edge.lengthMeters] (haversine fallback if an edge is missing,
  /// though that should never happen for paths produced by [adjacency]).
  double pathLengthMeters(List<int> path) {
    if (path.length < 2) return 0;
    double total = 0;
    for (int i = 0; i + 1 < path.length; i++) {
      final int a = path[i];
      final int b = path[i + 1];
      final List<int> aEdges = adjacency[a] ?? const <int>[];
      double? len;
      for (final int eid in aEdges) {
        final Edge e = edges[eid];
        if (e.other(a) == b) {
          len = e.lengthMeters;
          break;
        }
      }
      total += len ?? haversineMeters(nodes[a], nodes[b]);
    }
    return total;
  }
}

/// Haversine distance in meters between two LatLng points. Exposed as a
/// top-level helper so A* heuristic and tooling share the same formula.
double haversineMeters(LatLng a, LatLng b) {
  const double earthRadiusM = 6371000.0;
  final double lat1 = a.latitude * math.pi / 180.0;
  final double lat2 = b.latitude * math.pi / 180.0;
  final double dLat = (b.latitude - a.latitude) * math.pi / 180.0;
  final double dLng = (b.longitude - a.longitude) * math.pi / 180.0;
  final double s = math.sin(dLat / 2) * math.sin(dLat / 2) +
      math.cos(lat1) * math.cos(lat2) * math.sin(dLng / 2) * math.sin(dLng / 2);
  final double c = 2 * math.atan2(math.sqrt(s), math.sqrt(1 - s));
  return earthRadiusM * c;
}
